apiVersion: apps/v1
kind: Deployment
metadata:
  name: aireconsile
  namespace: aireconsile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aireconsile
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aireconsile
    spec:
      containers:
      - image: ghcr.io/ravindukotta/aireconsile:f615a6d6b75c3887c568fe897eb209649c463346
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 10
        name: aireconsile
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 10
        resources: {}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health/liveness
            port: http
          periodSeconds: 2
        volumeMounts:
        - mountPath: /app/output
          name: output
        - mountPath: /app/logs
          name: logs
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: aireconsile-output
      - emptyDir: {}
        name: logs
status: {}
