apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aireconsile-output
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
